In [5]:
import numpy as np

inputs = [[1,2,3,2.5],
          [2,3,-1,2.2],
          [-1.5,2,3.3,-0.8]]

weights = [[0.2, 0.8, 0.9, -0.3],
           [0.5, -0.2, 1, 0.3],
           [-0.4, 0.82, 0.17, -0.23]]

biases = [2,3,0.5]

# Now weights2 has shape (3 neurons × 3 inputs)
weights2 = [[0.7, -0.1, 0.4],
            [-0.3, 0.9, -0.5],
            [0.1, -0.8, 0.33]]

biases2 = [1.5, -2, 0.8]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Layer 1
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Layer 2
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print(layer2_outputs)



[[ 5.51     1.6025  -3.55225]
 [ 4.0556  -0.96    -0.83428]
 [ 6.96    -1.2765  -1.32695]]
